services:
  - type: web
    name: wins-agency-backend
    env: node
    region: oregon
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
